apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
spec:
  serviceAccountName: webhook-receiver
  triggers:
    - template:
        name: webhook-receiver
      bindings:
        - ref: webhook-receiver
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cayo-next-
      spec:
        params: 
          - name: app-name
            value: cayo-next
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/cayo-moraes-next
          - name: image-repo
            value: quay.io/cayops/cayo-next
          - name: app-namespace
            value: cayo-next-dev
        pipelineRef:
          name: cayo-next-pipeline
        serviceAccountName: build-robot
        workspaces:
        - name: pipeline-shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce 
              resources:
                requests:
                  storage: 1Gi
        - name: git-ops-repo
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
              accessModes:
              - ReadWriteOnce
        - name: git-credentials
          secret:
            secretName: mycredentials-github
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
rules:
  - resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    apiGroups:
      - triggers.tekton.dev
    verbs:
      - get
  - resources:
      - pipelineruns
      - pipelineresources
    apiGroups:
      - tekton.dev
    verbs:
      - create
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
roleRef:
  name: webhook-receiver
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: webhook-receiver
    kind: ServiceAccount
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-receiver
  namespace: cayo-next-pipeline
spec:
  port:
    targetPort: 8080
  to:
    name: el-webhook-receiver
    kind: Service
    weight: 100